gitx/gitx

Classes/git/PBGitIndex.m, Classes/git/PBGitRepository.h, Classes/git/PBGitRepository.m
About 80-300x faster, although still only taking milliseconds previously.
=> Parse refs with ObjectiveGit

Classes/git/PBGitIndex.m
In some (obscure[1]) cases, git would report problems on its stdout instead
of the expected even-lines text we want. This hardens the index refresh
by checking that the task didn't error, and that it was successful.
1 - like git mv-ing submodules around
=> Correctly report index refresh failures instead of asserting

Classes/Controllers/ApplicationController.m, GitX.xcodeproj/project.pbxproj, Scripts/build.py
Update Sparkle to 1.16.10 and correct the build script.
=> Sparkly things

Classes/Util/ObjectiveGit+PBCategories.h, Classes/Util/ObjectiveGit+PBCategories.m, Classes/git/PBGitCommit.h, Classes/git/PBGitCommit.m, Classes/git/PBGitGrapher.mm, Classes/git/PBGitRevList.mm, GitX.xcodeproj/project.pbxproj
I've been trying to pinpoint the memory leak in #ref-needed, but didn't succeed.
So, in the meantime, here's a few tidbits of Instruments lore.
=> Some optimizations

Classes/Controllers/PBGitSidebarController.m
This is a bit more discoverable than double-clicking the submodule row (at least for me).
=> Added "Open Submodule" menu item to contextual menu of submodules

.travis.yml
It was trying to build with Xcode 7.1, which no longer exists on Travis.
=> Change Travis to Xcode 8.3

Classes/Util/PBEasyPipe.m
Fix for https://github.com/gitx/gitx/issues/86.
=> Fix for indexing forever spinner

Classes/git/PBGitRepository.m, Resources/XIBs/PBCommitHookFailedSheet.xib
The commit hook error was showing (null) instead of the commit hook output.
=> Commit hook fix

Resources/html/views/history/history.js
=> Fix hyperlinks in commit messages

Resources/XIBs/PBGitCommitView.xib
=> Align commit view elements

Classes/Controllers/PBGitSidebarController.m
=> Checkout a branch when it is double-clicked in the sidebar

Classes/Views/PBRefMenuItem.m
=> Fix "Copy Short SHA"

Classes/Controllers/PBGitHistoryController.h, Classes/Controllers/PBGitHistoryController.m, Classes/PBCommitList.m
I wanted this for sooo long, hope you guys find that useful. It's wired to "⌃↓" for now, but it's open to  suggestions.
=> Add a method to move down to the previous commit in branch

.gitmodules, GitX.xcodeproj/project.pbxproj, GitX.xcodeproj/xcshareddata/xcschemes/GitX.xcscheme, GitX.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Scripts/build_objective_git.py
Also update submodules, some Xcode 11 noise, and add a script for building objective-git.
=> Rewire/fix MGScopeBar compile errors, etc.

.gitmodules, Classes/Controllers/PBGitHistoryController.m, GitX.xcodeproj/project.pbxproj, GitX.xcodeproj/xcshareddata/xcschemes/GitX.xcscheme, GitX.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Scripts/build_objective_git.py
=> Suppress rescroll when repo is updated externally

Resources/Credits.html
Better reflects where updates are to be expected.
=> Update URL in the About dialog box

Classes/Controllers/PBGitHistoryController.m
=> Revert "Suppress rescroll when repo is updated externally"

GitX.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
It's about to get rid of this
Same here https://github.com/gitx/MGScopeBar/pull/5
=> Add shared user data

.github/workflows/BuildPR.yml
All pull request and any merge to `master` will be build
=> Build master on CI

Resources/Info.plist
The feed is from 2014 and makes no sense
=> Disable automatic updates and checks

GitX.xcodeproj/project.pbxproj
It includes https://github.com/gitx/gitx/pull/234 except the https://github.com/gitx/objective-git changes, which are already on master there
=> VALID_ARCHS Apple Silicon support

Classes/Controllers/PBWebHistoryController.m, GitX.xcodeproj/project.pbxproj
=> Fixed "Show whitespace differences"

.github/changelog-configuration.json
close https://github.com/gitx/gitx/issues/287
=> Release notes on releases

.github/changelog-configuration.json, .github/workflows/BuildRelease.yml
It's about Sparkle update mechanism work https://github.com/gitx/gitx/issues/279#issuecomment-1042943677
=> Trigger a rebuild of appcast.xml on release

Classes/git/PBGitRepository.m
This commit allows GitX to respect the `core.hooksPath` option if it is set in the git config for the current repository.
=> Look for hooks in core.hooksPath if it is set

.github/workflows/BuildPR.yml
Thanks to the sponsor MacStadium !
=> Build pull request with Apple Silicon M1

.github/workflows/BuildRelease.yml
We just to name tag with 'beta' or 'alpha'
=> Add ability for a pre-release

Classes/git/PBGitIndex.m
This adds a config check for `commit.gpgSign` and changes the returned error to at least point the user at the underlying issue.
Slightly improves the situation over #326.
=> Consult the configuration whether to sign commits or not

Classes/Controllers/PBGitHistoryController.m
This adds a handler for double-clicks on the branch labels in history view so that a checkout is performed automatically.
I remember wondering why that feature was broken in the new release. Cheers to private `develop` branches, I guess 😉.
=> Wire double-clicks on refnames in commit list to checkout

README.markdown
The discussion was closed 5 years ago. !
=> Remove an outdated discussion in README

.github/workflows/BuildPR.yml
On a fork the variables are missing
=> Run notarization not from fork pull requests

Resources/html/css/GitX.css
=> Fix "Gist it" appearing despite being disabled in Settings

.gitignore, GitX.xcconfig, GitX.xcodeproj/project.pbxproj, README.markdown
* ~Enable Xcode to automatically manage signing.~ _This is removed._
* Create a `GitX.xcconfig` file and set it as config for the GitX target.
* Add instructions to create a `Dev.xcconfig` file.
* Add this file in `.gitignore`.
* Add instructions to find Development Team ID and certificate name.
Fixes #366
=> Fix the local build in Xcode

GitX.xcodeproj/project.pbxproj
This removes that utility's special "Install" configuration, which I'm not sure is even in use.
=> Remove Install configuration on gitx_askpasswd

.github/workflows/BuildPR.yml
master is broken on arm64 runner 
https://github.com/gitx/gitx/pull/391
=> Fix for arm64 runner

.github/workflows/BuildRelease.yml
Thanks to the feedback of @ADTC https://github.com/gitx/gitx/pull/392#issuecomment-1465192271,  it fixes now the release as well
=> Fix for arm64 runner (release)

.github/workflows/BuildPR.yml, .github/workflows/BuildRelease.yml
The goal is to automate the release of a new version to brew
=> Automate brew publish
