gitx/gitx

Classes/Controllers/PBWebHistoryController.m
html/views/history/history.css
html/views/history/history.js

Before:
After:
It would be nice to show a bar graphic like text diffs, but that can be in another PR.

Display size changes for binary files

---

Classes/git/PBGitIndex.m

`update-index -z` is set, so paths must be NUL delimited and not quoted.
See https://github.com/git/git/blob/v2.11.0/builtin/update-index.c#L525-L531

Fix unstaging new files

---

Classes/Views/GitXTextView.h
Classes/Views/GitXTextView.m
Classes/Views/PBCommitMessageView.h
Classes/Views/PBCommitMessageView.m
GitX.xcodeproj/project.pbxproj

Supersedes #3.
- This only affects the commit message text view, and not the search field.
- Spelling and grammar check (underlining only) settings appear to be already persisted automatically.
- The smart quotes quote type selected in the Show Substitutions window is not persisted as I don't see an API to access it. This probably doesn't matter.
- `PBGitDefaults` exists for handling preferences, but I think this is cleaner self-contained. Properties can be moved over later if needed.
- Lots of boilerplate, but I think everything matches up. An X macro might be nice here, but then we're using an X macro.

Remember text substitution preferences

---

Classes/Controllers/PBWebChangesController.m
Classes/Controllers/PBWebController.m
html/views/commit/commit.js

Implements the second item of #9, although it doesn't remove the inline copy button.
I also fixed a bug where the first line selected sometimes doesn't get copied.

Connect diff copying to the standard copy: menu item

---

Classes/git/PBGitTree.m

This enables following renames when viewing a file's history. Handy !

Enable --follow in the log

---

html/views/commit/commit.css
html/views/commit/commit.js

This should fix #9.
Also display both action buttons for the selected
lines in the same colour (white) as they also have
the same colour for each hunk.

In Diff/Commit view display »Stage« Button consistently at the left

---

.gitmodules

`git://` doesn't work directly in many organizations due to firewalls

Changed submodules git paths to https:// scheme

---

Classes/Controllers/PBHistorySearchController.m

Regressed in [dddc3e9#L339](https://github.com/gitx/gitx/commit/dddc3e9af2115d4f8ab78d2ef3177d912b6d1b9e#diff-042bf19bcba79b29164dbbcc16ba39a6L339)
Fixes #37

Set the searchMode ivar in its setter again

---

Classes/Controllers/PBGitHistoryController.h
Classes/Controllers/PBGitHistoryController.m
Classes/PBCommitList.h
Classes/PBCommitList.m

This was a tentative fix for the weird behavior of the `Edit > Copy patch` (eg. ⌃⌥⌘C) menu item when you whack modifiers around, but this isn't it. I've checked the various `-validateMenuItem:` method we have, to no avail.

Move the copy methods to the relevant controller

---

Classes/Views/PBCreateBranchSheet.m

This is the same class of bug that was fixed in https://github.com/rowanj/gitx/issues/24 (https://github.com/rowanj/gitx/commit/af59c91ea82fd08cdff8af10b5cf1ff190eac42b).
The ownership model here is still rather fragile. I don't think sheets are intended to have action targets with the same lifetime as their window. Perhaps the sheet window should hold a strong reference to its window controller? (Inverting the usual relation.)
Fixes #31 and supersedes #33.

PBCreateBranchSheet was deallocating itself mid-message

---

Classes/Controllers/PBWebHistoryController.m
Resources/html/views/history/history.js

The option to show file moves in a single line
rather than a separate remove and add is not one
to set when creating the diff. It has to be used
to manipulate that diff in an additional step.
As all the parameters used here as NSString /
NSNumber-typed the compiler couldn’t detect
the option being passed to the wrong method :/
Also adapted the JS to display the file moving
again.
This behaviour was introduced in 7af30a7. It
should fix the issue described in #46.

Fix display of renames (#46)

---

Classes/Util/PBEasyPipe.m
Classes/git/PBGitBinary.m

Use a regex to extract the version number. (E.g. when configuring
Xcode to use GuardMalloc, the text we capture contains some
GuardMalloc-related text as well. This change makes extracting
the version number more stable against that. It does seem, however,
that other parsing tasks in GitX will not cope well with that
situation, either).
Do a numerical compare for the version number. (Seeing that git
does allow two digit sub-versions in the current 2.11, doing a
pure string comparison isn’t sufficient.)

Improve git version detection

---

Classes/Controllers/PBRefController.h
Classes/Controllers/PBRefController.m
Classes/Views/PBRefMenuItem.m

Looking at these I started wondering whether it’d be a good idea
to remove the inactive items in there.
I can see the point of them
making things more consistent across menus – but the idea of a
contextual menu started off focusing on the commands that are actually
usable in the current context.
Besides, the menus are already quite long.

Make ref contextual menus localisable

---

Classes/PBGraphCellInfo.m
Classes/PBMacros.h
Classes/PBMacros.m
Classes/Util/ObjectiveGit+PBCategories.h
Classes/Util/ObjectiveGit+PBCategories.m
Classes/git/PBGitGrapher.mm
Classes/git/PBGitRevList.mm

This reverts a change I did recently w.r.t to how we enumerate commits.
This should make the "broken" lane bug go away, at the expense of more lanes in some cases. As for the underlying issue, I don't really know why this happens. I suspect libgit2 doesn't revwalk in the same way as Git does, but I don't really have time to check what really differs...

Fix missing parents

---

Classes/Controllers/PBGitCommitController.h
Classes/Controllers/PBGitCommitController.m
Classes/Controllers/PBGitRepositoryDocument.m
Classes/Controllers/PBGitWindowController.h
Classes/Controllers/PBViewController.h
Classes/Controllers/PBWebChangesController.h
Classes/Views/PBCommitMessageView.h
Classes/Views/PBCommitMessageView.m
Classes/Views/PBFileChangesTableView.m
Classes/git/PBGitRepository.h
Classes/git/PBGitRepository.m
Resources/XIBs/PBGitCommitView.xib

Documents, view controllers, and repositories were getting leaked when closing documents.
This fixes various overretains, retain cycles, and other issues exposed once things started getting released.

Fixed documents and repositories leaking when closing documents

---

Classes/Controllers/PBPrefsWindowController.m

The general icon went missing when gitx.icns was removed.

Fixed missing General preferences icon

---

Classes/Controllers/PBWebController.m
Classes/git/PBGitXProtocol.m
Resources/html/lib/diffHighlighter.js

I found a few issues with the diff viewer, like inline images not working, and some "missing" files info.
The first was that I'm running with diff.mnemonicprefix set, which the diff parser didn't expect.
The second is that files with no diff at all (like simple renames) were skipped when building the HTML.

Little fixes to the diff viewer

---

Classes/Controllers/ApplicationController.m

This pull request refers to #74, where only files can be selected in the open panel. It should be exactly the other way around where only folders can be opened.

Fix open panel only accepting files

---

Classes/Controllers/PBGitCommitController.m
Resources/English.lproj/MainMenu.xib

Bindings can make the menu item behavior act erratically because the binding state is shared across the app, not per-document.
This also adds a checkmark to the menu item when amending is active.
Steps to reproduce a problem like this:
- Open a repository
- Select Amend Commit to start amending
- Close the repository
- Open the same repository
- Select Amend Commit to start amending again
- This time the menu item sets amend to NO instead of YES, so nothing happens the first time you select the menu item

Change Amend Commit menu item to use an action instead of bindings

---

Scripts/build.py
requirements.txt

This simplifies the build setup by removing external python dependencies. It eliminates this common problem: https://github.com/gitx/gitx/wiki/Build-instructions#no-module-named-argh
The functionality of the script remains the same. We replace `argh` with python's own `argparse`. And since `argcomplete` isn't used anywhere, we can also remove `requirements.txt`.
`./Scripts/build.py build debug`, `./Scripts/build.py build release`, `./Scripts/build.py config debug` and `./Scripts/build.py config release`, all work.

build.py: Remove argh dependency

---

Classes/Controllers/OpenRecentController.m

Repositories that no longer exist shouldn't appear in Open Recent.

Don't include deleted repositories in Open Recent

---

Classes/git/PBGitHistoryList.m
Classes/git/PBGitRevList.h
Classes/git/PBGitRevList.mm

This prevents multiple loadRevisions from being called at once, which could crash when trying to reload a large repository multiple times rapidly.

Switch to using NSOperation and NSOperationQueue in PBGitRevList

---

Classes/gitx.m

Set the SBApplication instance's sendMode to kAENoReply to speed up how quickly gitx terminates
Without this it was waiting for the Apple Event to respond, which could result in the gitx command line app staying open for a few seconds as it waits for the reply. This happened frequently when trying to open a repository that was already open.

Sped up how quickly gitx CLI terminates when opening an already open repository

---

Classes/Views/GLFileView.h
Classes/Views/GLFileView.m
Resources/html/css/GitX.css
Resources/html/lib/GitX.js
Resources/html/lib/diffHighlighter.js
Resources/html/views/blame/blame.js
Resources/html/views/blame/index.html
Resources/html/views/commit/commit.js
Resources/html/views/commit/index.html
Resources/html/views/commit/multipleSelection.js
Resources/html/views/commit/test.html
Resources/html/views/diff/diffWindow.js
Resources/html/views/diff/index.html
Resources/html/views/fileview/index.html
Resources/html/views/fileview/index_test.html
Resources/html/views/history/history.css
Resources/html/views/history/history.js
Resources/html/views/history/index.html
Resources/html/views/log/format.html
Resources/html/views/log/index.html
Resources/html/views/log/log.js
Resources/html/views/log/test.html
Resources/html/views/source/index.html
Resources/html/views/source/source.js

It appears that the HTML view code was not originally written with XSS in mind, with nearly all text being interpreted as raw HTML. If a user opens a repository with malicious commits, arbitrary JavaScript could be run.
I've fixed all of the code injection bugs I could find, and have also added Content-Security-Policy headers to each of the views to mitigate possible remaining or future injection bugs. Inline scripts and styles have been moved into external files as needed.

Fix and mitigate code injection (XSS) in HTML views

---

Classes/Controllers/PBGitWindowController.m
Classes/Views/PBRefMenuItem.m
Classes/git/PBGitRepository.h
Classes/git/PBGitRepository.m

This adds a reset option that uses `--soft`. I guess maybe it could use `--mixed` instead which is the default for git but I think `--soft` is a bit more expected. Once you work out what they typically awful naming means anyway - why not `--unstaged`, `--staged`, and `--discard`? Ugh git.
Sorry if I already did a pull request for this - forgot I had this code and found it lying around.

Add reset option

---

Resources/XIBs/PBGitHistoryView.xib

I'm sorry, but this is another one of my "stab in the dark" PRs. I don't know what I'm doing, but this seems to work. I have been using a build off of master (from 57ed8a0) and just noticed that the relative date formatting was not working correctly (as in: at all). This PR is an attempt to reconnect the relative date column with the relative date formatter.
I'm really not kidding when I say I don't know what I'm doing. I just did a lot of `grep`ing and guessing about how to get things connected, so it would not surprise me to find out that I did something wrong. Any commentary, pointers or review are welcome. 😄 
I use this app every day and would love to help more, but Objective-C/Cocoa/XIB/Xcode are hard for me to get to used to.

Fix relative dates in history view

---

Classes/Controllers/PBGitCommitController.m

Ensure the commitMessageView.typingAttributes dictionary is not nil before setting properties on it.
Fixes #173
Fixes regression from a1184707748e3aa8e2a659ad6458f695dce00f93 on 10.13

Fix commit message font on 10.13

---

Classes/gitx.m

This makes the window open in the current Space, instead of where the current main window is, which would have triggered a Space switch.
I'm putting that there for discussion, as I'm really tempted to just merge it anyways since I have been wrangling GitX windows every time I open one for quite some time now…

Activate GitX after opening the repository

---

Classes/Util/PBTerminalUtil.m
Classes/git/PBGitDefaults.h
Classes/git/PBGitDefaults.m
Classes/iTerm2GeneratedScriptingBridge.h
GitX.xcodeproj/project.pbxproj
Resources/Info.plist

This is a rejig of #166, because it didn't work when I tried it on 10.14 (*cough* AEpocalypse *cough*), reworked the code so it's nicer and has a semblance of error-reporting, and removed the `login` dependency by using a method from a pristine `sdp`-generated header.
@Timmmm Care to give it a spin ?
```
defaults write net.phere.GitX PBTerminalHandler -string com.googlecode.iterm2
```

iTerm2 support

---

Classes/Controllers/PBWebChangesController.m
Classes/Controllers/PBWebController.m
Classes/PBCommitList.m
Resources/XIBs/PBGitHistoryView.xib
Resources/html/css/GitX.css
Resources/html/lib/GitX.js

This PR adds additional CSS and on-load hooks in order to make the HTML content of the app appear dark when the user's system is set to use dark mode in macOS Mojave.
e.g.

Switch to dark HTML content when user's system is dark

---

Classes/Controllers/PBHistorySearchController.m
Classes/Controllers/PBHistorySearchMode.h

This allows you to use the GUI with standard git-log based arguments. I don't think you can beat the command-line syntax.

Add a "raw" mode to the search filters

---

.travis.yml

The Travis build has failed for each commit for some time but the build error is suppressed due to using a pipe with `xcpretty`. This fixes the suppression of build errors.

Indicate failing Travis builds

---

.gitmodules

In the current submodule there is a message 'The project has moved to https://github.com/syntaxhighlighter'
The old one has only 2 README.md commits more but is _some_ commits behind

More modern Syntaxhighlighter submodule

---

Resources/html/views/history/history.css
Resources/html/views/history/history.js
Resources/html/views/history/index.html

Originally I wanted to get rid of fields jumping due to height change. In the end I flattened multi-level table structure and converted view to 3 possible states:
- when name, email and date of author and committer are same, then only author info is shown
- when name and email are same, but date is different, then additional commit date is shown in author info
- when name or email of author and committer are different, then author and committer info are shown separately.
Plus a bit of cleanup

Cleanup commit header in history view for elements to stay in place

---

Classes/Controllers/PBGitRepositoryDocument.m

This will detect if a repository gets deleted or moved and will close the document instead of trying to read from the old path and potentially crashing.
For the future:
It would be even better to automatically update the repository to the new location, but the current architecture makes that a bit messy. If the nested NSDocument classes get cleaned up we could reallocate the GTRepository and reuse the document.

Use NSFileCoordinator to listen see if the repository is deleted or moved

---

Classes/Controllers/PBGitCommitController.m
Classes/Controllers/PBGitHistoryController.m
Classes/Controllers/PBGitSidebarController.m
Classes/Controllers/PBViewController.h
Classes/Controllers/PBViewController.m
Classes/git/PBGitGrapher.h
Classes/git/PBGitGrapher.mm
Classes/git/PBGitHistoryGrapher.m
Classes/git/PBGitRevList.m

Fixes a crash introduced by bb8a5169c639a6bb148e58d421627516976f8ae5 and does some incremental cleanup that I performed while looking for the crash (remove unnecessary passing of PBGitRepository in arguments and removed instance variables marked with a FIXME).

Fix crash and miscellaneous cleanup

---

Classes/Controllers/PBGitCommitController.m

Drag and drop in NSTableView became more strict on 10.14.
Use setPropertyList:forType: to silence this exception when dragging:
> There are 2 items on the pasteboard, but 1 drag images. There must be 1 draggingItem per pasteboardItem.

Fix exception when dragging files in the unstaged and staged changes table views

---

Classes/Controllers/PBGitCommitController.h
Classes/Controllers/PBGitCommitController.m
Classes/git/PBGitIndex.h
Classes/git/PBGitIndex.m
Classes/git/PBGitRepository.h
Classes/git/PBGitRepository.m
Resources/en.lproj/MainMenu.xib

This adds a menu item to run the `prepare-commit-msg` hook.
Another option would be to run the hook automatically, but since staging and writing the message don't happen in an explicit order that would get pretty complex (or slow if `prepare-commit-msg` takes a while to run).

Added menu item to Stage menu that can run prepare-commit-msg hook

---

.github/workflows/BuildPR.yml

This saves `.xcarchive` build artifacts, which include the prebuilt binaries for each CI run. This is my first time using Github Actions, so any pointers or advice are very welcome. After downloading and extracting, `GitX.app` is located at `GitX.xcarhive/Products/Applications/GitX.app`
This is based on:
- https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts
- https://github.com/utmapp/UTM/blob/master/.github/workflows/build.yml
- https://github.com/utmapp/UTM/blob/master/scripts/build_utm.sh
(The latter 2 based @hannesa2's comment in https://github.com/gitx/gitx/issues/240#issuecomment-1014393822)
I followed UTMs lead and zipped the `.xcarchive` in CI, which I assume is just easier/faster for CI to deal with. However, when downloading artifacts, it zips …

ci: save build artifacts

---

.github/workflows/BuildPR.yml

This changes the CI artifact from a `.xcarchive` directory to `.dmg` that contains a working `GitX.app`. I'm not sure what I was running into yesterday when it seemed like the `.xcarchive` was important. I suspect that it had to do w/ the artifact upload CI workflow losing some Mac specific info from some files, but that's just a guess.
I went deep into using `xcodebuild` to export an app directly from the `.xcarchive`, but that appears to require developer certificates, signing, etc, so I abandoned that and went back to study how it's done by UTM (which I'm not familiar with and have never used, but which was shared by @hannesa2). They have a [`package_mac.sh`](https://github.com/utmapp/UTM/blob/master/scripts/package_mac.sh) script running in CI that has a pretty clear "unsigned" code …

Change CI artifact to dmg

---

GitX.xcodeproj/project.pbxproj

Now we have an automatic version number in gitx about for each pull request and each release version
This sample means it's 
* based on latest release `0.17`
* 5 commits ahead of this latest release 
* and git commit sha1 is `0bd21a4`

Automatic version

---

.github/changelog-configuration.json
.github/workflows/BuildRelease.yml

Only be create a new tag, eg 
```
git tag -a 0.17 -m "something" 
git push --tags
```
the release pipeline is now triggered. 
Here https://github.com/hannesa2/gitx/releases/tag/0.19.dmg you can see one of my test drives.
I will create late a new version to have a new baseline of releases

Release job

---

.github/workflows/BuildPR.yml
GitX.xcodeproj/project.pbxproj
GitX.xcodeproj/project.xcworkspace/contents.xcworkspacedata

It's a preparation for M1 and includes the breaking changes from https://github.com/gitx/gitx/pull/234
Because we have only x86 Github runner, it builds only x86

VALID_ARCHS with arm64

---

Classes/git/PBGitIndex.m

This is based on nanotech's patch here -- however using the `--gpg-sign` arg now seems to work.
https://github.com/gitx/gitx/issues/32#issuecomment-280474077
This is not a complete pull request because adding the arg for gpg signing
should only happen if one or maybe ALL of the following are true:
- A "GPG Sign" GitX preference is set to true
- A git `[commit]` setting in either a local or global .gitconfig includes: `gpgsign = true`
- The directory `~/gnupg` exists
The commit in this pull request created with my local build of GitX with this branch on an M1 Pro Mac is signed -- so it seems to work.

enable gpg signing

---

Resources/XIBs/PBGitHistoryView.xib
Resources/XIBs/PBGitSidebarView.xib
Resources/en.lproj/RepositoryWindow.xib

Just a try to fix https://github.com/gitx/gitx/issues/348.
- Added separator in main window footer area
- Added some extra spacing to toolbar segmented buttons
Disclaimer:
- Wasn't able to compile to test properly
- Was unsure which how many automatic modifications by Xcode I had to cut out again

Trying to fix visual glitches appearing on Mac OS 10.x

---

README.markdown

Direct readers to the Releases page to get the pre-built release so they can use it immediately. Also update the information about building from source code.

Improve the build & installation instructions

---

Resources/en.lproj/Preferences.xib

Fixes #219
* The window is wider, avoiding the overflow menu.
* The controls were all re-aligned and adjusted to look nicer with better spacing between them, and center aligned in the window.
* The numeric control is enforced now (doesn't accept non-numeric input) and a stepper is added.
* Some text labels and tooltips were improved.
Note that the changes were done using Xcode Storyboard, so the XML code was automatically generated.
Screenshots:

Improve the Settings (Preferences) window

---

.gitignore

These are generated by the build process (`xcodebuild`) and shouldn't be committed.

Ignore the generated build artifacts

---

.github/workflows/BuildPR.yml
.github/workflows/BuildRelease.yml

Fixes #362
@hannesa2 this cannot be fully tested in the forked PR because the CI step with the change will be skipped.
I partially tested it though in #377 by enabling the `Prepare artifact` step. The DMG files work correctly, but the GitX app won't run due to the lack of signing (which we fixed already in #376).
If needed to confirm a full test, please use an origin PR to do an integration test with `xcodebuild -exportArchive`.
- The generated DMG files should work correctly in both platforms. _(This works.)_
- Dragging GitX onto Applications should install it. Finder may ask to replace existing copy. _(This works.)_
- Installed GitX should run without issues or crashes. _(This doesn't work in forked PR due to lack of signing.)_

Add a link to Applications in the DMG file

---

GitX.xcodeproj/project.pbxproj
README.markdown

As we shouldn't expect a random contributor to have a sign-ready Apple Developer account, and building with the Hardened Runtime enables requires signing, disable it on the Debug configuration (which is the default, anything made using `xcodebuild` will use Release.
Fixes the build for me, since I got the same error than [this one](https://github.com/gitx/gitx/discussions/366#discussioncomment-5113536) but while trying to run in Xcode.

Remove ENABLE_HARDENED_RUNTIME from the Debug configuration

---

Resources/XIBs/PBGitHistoryView.xib
Resources/XIBs/PBGitSidebarView.xib
Resources/en.lproj/RepositoryWindow.xib

As this broke the sidebar auto-expanding behavior, let's revert this. Fixes #382.
This reverts commit 322e12284152e0787ad3d81e554b191d902454af.

Revert "Trying to fix visual glitches appearing on Mac OS 10.x"

---

Resources/html/css/shThemeDark.css
Resources/html/views/blame/blame.css
Resources/html/views/blame/index.html
Resources/html/views/fileview/index.html
Resources/html/views/fileview/index_test.html

The SH dark theme is the same as the following file, with formatting and minor modifications: `Resources/html/lib/syntaxhighlighter/styles/shThemeFadeToGrey.css`
Fixes #356
It takes care of the source code and blame views. Unfortunately I don't know how to apply dark background on [`MGScopeBar`](https://github.com/gitx/MGScopeBar) so for now I'm keeping it a draft. @hannesa2 please help with the bar. How do we make it have a dark background?
Screenshots:
Soucre:
Blame:

Implement a Dark theme for syntaxhighlighter and blame

---

.github/workflows/BuildPR.yml
.github/workflows/BuildRelease.yml

This makes it easier to skip and reintroduce x86 builds in CI

Swap order of x86 and arm64 builds in CI

---

.github/workflows/BuildPR.yml
.github/workflows/BuildRelease.yml

Build for x86 is broken since one year and we were not able to fix it. 
That's why I comment x86 support out in CI to have a proper build.
If you want to have further x86 support, please remove comment and try to fix it. I would happy to merge any pull request.

Drop x86 support

---

.github/workflows/BuildPR.yml
.github/workflows/BuildRelease.yml

macos-13 runners are going away very soon:
'This process will begin October 1, 2025, and the image will be fully retired on December 4, 2025.'

Github runner macos-15-intel
